trigger:
- main

parameters:
  - name: name
    displayName: Name_of_Resource
    type: string
    default: application
  
  - name: region
    displayName: Region
    type: string
    default: eastus
    values:
    - eastus
    - eastus2
    - northeurope
    - centralindia

  - name: vmSize
    displayName: VM_Size
    type: string
    default: D4s_v3
    values:
    - D2as_v4
    - DS2_v2
    - D4s_v3
    - DS3_v2
    - D8s_v3

  - name: vmStorageAccountType
    displayName: VM_Storage_Account_Type
    type: string
    default: Standard_LRS
    values:
    - Standard_LRS
    - StandardSSD_LRS
    - Premium_LRS
    - UltraSSD_LRS

  - name: imageSKU
    displayName: Image_SKU
    type: string
    default: 20.04-LTS
    values:
    - 16.04-LTS
    - 18.04-LTS
    - 20.04-LTS
    - 22.04-LTS

steps:
- script: |
    sed -i "s/{vm}/${{ parameters.name }}/g" terraform.tfvars
    sed -i "s/{Region}/${{ parameters.region }}/g" terraform.tfvars
    sed -i "s/{VMSize}/${{ parameters.vmSize }}/g" terraform.tfvars
    sed -i "s/{StorageAccountType}/${{ parameters.vmStorageAccountType }}/g" terraform.tfvars
    sed -i "s/{ImageSKU}/${{ parameters.imageSKU }}/g" terraform.tfvars
    cat terraform.tfvars
  displayName: 'Replace Values'

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.5.0' # Specify version explicitly if needed
  displayName: 'Install Terraform'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: '<YOUR_SERVICE_CONNECTION_NAME>'
    backendAzureRmResourceGroupName: 'jenkins_server'
    backendAzureRmStorageAccountName: 'asdfghjkasdf'
    backendAzureRmContainerName: 'backend'
    backendAzureRmKey: 'backend.tfstate'
  displayName: 'Terraform: Init'

- task: TerraformTaskV3@3
  inputs:
    command: 'validate'
  displayName: 'Terraform: Validate'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: '-lock=false'
    environmentServiceNameAzureRM: '<YOUR_SERVICE_CONNECTION_NAME>'
  displayName: 'Terraform: Plan'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: '<YOUR_SERVICE_CONNECTION_NAME>'
  displayName: 'Terraform: Apply'
